language: node_js
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

test:
  - npm test

script:
  - npm run build

deploy:
  provider: pages
  repo: guimarca.github.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master