language: node_js
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  repo: guimarca/guimarca.github.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  target_branch: master
  on:
    branch: master